### ISSUE TITLE
[Enhancement] Decoupled vessels have TCA enabled by default

### ISSUE THREAD

**Issue by jrodrigv** [allista/ThrottleControlledAvionics#28]
If your vessel is decoupled from your main vessel. TCA is enabled by default on the new child vessels. This can cause undesired effects.

It would be great if TCA is disabled by default for decoupled vessels. Or at least to have a configuration parameter for this.

**Comment by allista** [comment]
Thanks. I see the problem. And I think this should be an option, as in other situations the opposite is true.
Where would you recommend to place it?

**Comment by allista** [comment]
This is fixed by virtue of the new TCA Groups mechanics I introduced in the v3.5.3
