### ISSUE TITLE
Persistent Rotation and TCA Autopilot

### ISSUE THREAD

**Issue by dtrauma** [allista/ThrottleControlledAvionics#39]
There's some unfortunate interaction between the autopilot in this mod and persistent rotation: http://forum.kerbalspaceprogram.com/index.php?/topic/102277-122-persistentrotation-182/

PR preserves momentum and disables the "press warp to stop all momentum"-cheatiness of stock KSP. That also means that TCA orienting the vessel on a maneuver node and then warping leads to all kind of funny reorienting business after warp, sometimes missing the node completely.

Without making the mods aware of each other, the easiest fix would be to enable SAS right before warping and disable it again right after, as PR understands this to mean "I'd spend some energy keep this alignment" if you enter warp with only minimal momentum left, as TCA does.

**Comment by dtrauma** [comment]
Corresponding issue in PR
https://github.com/MarkusA380/PersistentRotation/issues/17

**Comment by allista** [comment]
Thanks!
That's actually a bug, since TCA has a code dedicated to this. It just don't work as expected. Interestingly, I play with PR and never had trouble with the minimal momentum approach. Nevertheless, I'm fixing it.
