### ISSUE TITLE
Drawing lines from modules selection window

### ISSUE THREAD

**Issue by arekbulski** [allista/ThrottleControlledAvionics#47]
In hangar (editor mode) there are two TCA windows: main and modules selection. If I click toolbar icon, both windows close but there are still lines drawn that are part of the modules window. If I close that window using a button in main window, it doesnt. 

This is not a huge issue, clearly there is a workaround.

I will attach screenshots asap.

**Comment by allista** [comment]
Thanks for the report!

**Comment by arekbulski** [comment]
I cannot make a screenshot because when I reinstall TCA (even certified for KSP 1.3) it just buggs the game completely. I kind of gave up on using TCA.
