### ISSUE TITLE
No In-flight menu

### ISSUE THREAD

**Issue by OfficiallyBrown** [allista/ThrottleControlledAvionics#50]
I was previously using 1.2.2 and had everything working correctly. I had updated to 1.4, with TCA 3.5 and a couple other mods. The TCA button shows up in the editor and I can configure everything fine, but upon launching the craft, there is no TCA window to control the flight. The TCA button in the applauncher is green, but clicking on it does nothing, there is no option to enable a TCA button in blizzy's toolbar, and pressing y does enable/disable TCA. It seems to be working, as my craft will hover and the throttle will adjust, but there's no way to really do anything as there is no menu

Also, this is in sandbox, so everything should be unlocked/enabled. In the part window it says TCS is intalled.
Theres no error or crash, so I don't really know if there's any reports to look for.

**Comment by allista** [comment]
TCA 3.5 is not compatible with KSP-1.4
Wait for an update soon (this week for sure).

**Comment by OfficiallyBrown** [comment]
Ahh, my bad. I was using ckan and must've missed the compatibility note
