### ISSUE TITLE
cant install it properly need directions for 3.5.2 manual install

### ISSUE THREAD

**Issue by Swoop376** [allista/ThrottleControlledAvionics#58]
i dowloaded 3.5.2 trottlecontroled and AT_utils latest version (came in a master folder) both zip files contained gamedata and other files im not sure where to put them. i tried many things already like extracting the gamedata content into the gamedata of my ksp install 1.4.3 i see the modules in the R&D buildings they are unlocked but not installed to any of my pods. No tca buttons on my toolbar nothing.i dont really know what im doing wrong i was using 1.3.1 version of it but i had no control windows available in flight so i tried your new version..i really hope you can help with that. 

Thanks alot

**Comment by allista** [comment]
To address this you have to provide the **KSP_Data\output_log.txt** (Player.log on mac/linux, elsewhere)

In any case this sounds like installation problem.
Manual installation is straight-forward: just download TCA from SpaceDock and copy the GameData from the archive into KSP main folder, overwriting any conflicts. It already contains necessary components from AT_Utils.
