### ISSUE TITLE
After TCA places a node, Precise Maneuver no longer works

### ISSUE THREAD

**Issue by alexandruast** [allista/ThrottleControlledAvionics#64]
Reproduce:
- Have Precise Maneuver plugin installed.
- Place a few maneuver nodes and confirm there are no errors.
- In orbit, run Orbital Autopilot -> Land.
- Abort the command, delete the node.
- Place a maneuver node again manually, Precise Maneuver won't come up, and it throws an error: 
```
[EXC 07:27:18.486] NullReferenceException: Object reference not set to an instance of an object
	KSPPreciseManeuver.NodeTools.GetTargetOrbit (.CelestialBody refbody)
	KSPPreciseManeuver.NodeManager.UpdateNodes ()
	KSPPreciseManeuver.PreciseManeuver.Update ()
```

**Comment by allista** [comment]
This should definitely be reported to the Precise Maneuver repo.

**Comment by radistmorse** [comment]
What exactly does the land autopilot do? The only way this exception can happen is when the targeted entity has no orbit (FlightGlobals.fetch.VesselTarget.GetOrbit () == null). As far as I know this situation is impossible in vanilla game.

**Comment by allista** [comment]
Yea, TCA implements custom ITargetable that is just a lon-lat-alt point on the surface without an orbit. After using-and-aborting the autopilot the target point remains the current vessel's target (it may be deleted via TCA's main window, Orbital Tab).

**Comment by allista** [comment]
https://github.com/allista/ThrottleControlledAvionics/blob/1e45137881a2da003007fe7a51f3d881730446be/Navigation/WayPoint.cs#L187

**Comment by alexandruast** [comment]
Any plans on this? I'll be more than happy to contribute, but have no programming experience in unity and it will take a while :)

**Comment by allista** [comment]
From TCA's point of view this waypoints work as designed. There's absolutely no need for them to have a dummy orbit and in any case there's no contract attached to `ITargetable` that says `GetOrbit()` should not return `null`.
