### ISSUE TITLE
Number input in UI also triggers the corresponding action groups

### ISSUE THREAD

**Issue by allista** [allista/ThrottleControlledAvionics#99]
> In hover mode, when I type in a desired altitude the action groups associated with those number keys also get triggered.

> For example, '2' toggles the downward engines on/off & '0' opens the cargo bay ramp.  So when I type '250' into the altitude widget to set my altitude at 250 meters, it also triggers the action groups to turn off my lift engines and open the cargo ramp.  Not good when you're in-flight!

**Comment by tjanke42** [comment]
Thanks for taking care of this!  You rock!
